package application;

import javafx.fxml.FXML;
import javafx.scene.layout.AnchorPane;
import javafx.event.ActionEvent;

public class LoginSceneController {

	// Event Listener on Button.onAction
	AnchorPane parent;

	@FXML
	public void login(ActionEvent event) {
		// TODO Autogenerated
	}
	
}
